// ===============================================================
//  ⚠ WARNING: THIS FILE IS AUTO-GENERATED BY SiCADA v1.0.0
// ---------------------------------------------------------------
//  DO NOT EDIT THIS FILE MANUALLY!
//  Any changes will be overwritten when the code is regenerated
//  and may cause unexpected behavior.
// ---------------------------------------------------------------
//  Auto-generated:  2025-10-16 14:15:40
// ===============================================================

public static partial class SiCADA
{
    public static ctest? test;
    public partial class ctest : S7Accumulator
    {
        // DB_DECLARATIONS
        // END_DB_DECLARATIONS
        public ctest
            (
            int accumulatorPort,
            S7.Net.CpuType cpuType,
            string plcIp,
            short plcRack,
            short plcSlot
            ) : base
            (
                accumulatorPort, 
                cpuType, 
                plcIp,
                plcRack,
                plcSlot
            )
        {
            // DB_INSTANTIATIONS
            // END_DB_INSTANTIATIONS
        }
    }
}
