#!/usr/bin/env python3
"""
S7SiCADA.py – SiCADA Python CLI Tool
Author: Marko Lazarević
Version: 1.0.0

Description:
    S7SiCADA is a Python-based utility that auto-generates C# code
    from Siemens TIA Portal .db source files.

Usage Examples:
    $ S7SiCADA --plc-prefix MyPLC --tia-portal-source ./MyDB.db
    $ S7SiCADA --list
"""

from __future__ import annotations
import argparse
import logging
import sys
from typing import Optional
from pathlib import Path

__author__ = "Marko Lazarević"
__version__ = "1.0.0"
AGP = Path(__file__).resolve().parent.parent.joinpath("src", "AutoGenerated")

# -----------------------------------------------------------------------------
# Logging Setup
# -----------------------------------------------------------------------------
def configure_logging(verbose: bool = False) -> None:
    """Configure logging output format and verbosity."""
    level = logging.DEBUG if verbose else logging.INFO
    logging.basicConfig(
        level=level,
        format="%(asctime)s [%(levelname)s] %(message)s",
        datefmt="%H:%M:%S",
    )


# -----------------------------------------------------------------------------
# Business Logic
# -----------------------------------------------------------------------------

def add_plc(plc_name: str) -> None:
    """
    Add a new PLC by creating a folder under the AutoGenerated directory.

    Args:
        plc_name (str): Name of the PLC to add.
    """
    # Sanitize the name (optional: remove spaces or invalid characters)
    sanitized_name = plc_name.strip()
    if not sanitized_name:
        logging.error("PLC name cannot be empty or whitespace.")
        sys.exit(1)

    plc_path = AGP / sanitized_name

    try:
        plc_path.mkdir(parents=True, exist_ok=False)
        logging.info(f"✅ PLC '{sanitized_name}' added successfully at {plc_path}")
        print(f"PLC '{sanitized_name}' has been added.")
    except FileExistsError:
        logging.warning(f"⚠ PLC '{sanitized_name}' already exists at {plc_path}")
        print(f"PLC '{sanitized_name}' already exists.")
    except Exception as exc:
        logging.exception(f"Failed to create PLC directory '{sanitized_name}'")
        sys.exit(1)

    file_path = plc_path / "placeholder.cs"

    # Write something into the file (optional)
    file_path.write_text("// This is a placeholder for PLC code\n")

    print(f"Created file: {file_path}")


    sys.exit(0)


def list_plcs(directory: Path = Path(".")) -> None:
    """List contents of the specified directory."""
    logging.info("📂 Listing existing PLCs")
    for item in sorted(AGP.iterdir()):
        print(f" - {item.name}")
    sys.exit(0)


def validate_args(args: argparse.Namespace, parser: argparse.ArgumentParser) -> None:
    """Additional validation after parsing."""
    if not args.plc_prefix.strip():
        parser.error("--plc-prefix cannot be empty or whitespace.")

    source = Path(args.tia_portal_source)
    if not source.exists():
        parser.error(f"TIA Portal source file not found: {source}")


# -----------------------------------------------------------------------------
# CLI Parser
# -----------------------------------------------------------------------------
def parse_args(argv: Optional[list[str]] = None) -> argparse.Namespace:
    """Parse and validate command-line arguments."""
    parser = argparse.ArgumentParser(
        prog="S7SiCADA",
        description="S7SiCADA — Auto-generate C# code based on TIA Portal .db source files.",
        epilog=(
            "Example usage:\n"
            "  S7SiCADA --plc-prefix MyPLC --tia-portal-source ./MyDB.db\n\n"
            "Example in C#:\n"
            "  S7SiCADA.MyPLC.myDb.myVar.CV = 3.14;"
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )

    parser.add_argument(
        "-a", "--add-plc",
        help="List current directory contents and exit.",
    )

    parser.add_argument(
        "-l", "--list",
        action="store_true",
        help="List current directory contents and exit.",
    )

    parser.add_argument(
        "-p", "--plc-prefix",
        metavar="PLC_PREFIX",
        help="Prefix used to access PLC data (e.g., 'MyPLC').",
    )

    parser.add_argument(
        "-s", "--tia-portal-source",
        metavar="PATH",
        help="Path to the TIA Portal .db source file (e.g., './data/MyPLC.db').",
    )

    parser.add_argument(
        "-v", "--version",
        action="version",
        version=f"%(prog)s {__version__}",
    )

    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Enable verbose (debug) output.",
    )

    args = parser.parse_args(argv)

    configure_logging(args.verbose)

    # Handle special mode early
    if args.list:
        list_plcs()

    if args.add_plc:
        add_plc(args.add_plc)

    # Require both args for generation mode
    if not args.plc_prefix or not args.tia_portal_source:
        parser.error("Both --plc-prefix and --tia-portal-source are required unless using --list.")

    validate_args(args, parser)
    return args


# -----------------------------------------------------------------------------
# Main Entry Point
# -----------------------------------------------------------------------------
def main(argv: Optional[list[str]] = None) -> None:
    """Main entry point for the CLI."""
    try:
        args = parse_args(argv)
        logging.info("✅ S7SiCADA started successfully.")
        logging.debug(f"Arguments: {args}")

        # Placeholder for main logic
        print(f"Generating C# code for PLC '{args.plc_prefix}' using source '{args.tia_portal_source}'")

    except KeyboardInterrupt:
        logging.error("Operation cancelled by user.")
        sys.exit(1)
    except Exception as exc:
        logging.exception("Unhandled error occurred.")
        sys.exit(1)


if __name__ == "__main__":
    main()
