// ============================================================================
//     WARNING: THIS FILE IS AUTO-GENERATED BY THE SiCADA
//     ========================================================================
//     DO NOT EDIT THIS FILE MANUALLY. Any changes you make here will be lost
//     when the code is regenerated, and may cause incorrect behavior.
//
// Generated:   2025-10-14
// ============================================================================

using static SiCADA;

public static partial class SiCADA
{
    public static cMyPlc? MyPlc;
    public partial class cMyPlc : S7Accumulator
    {
        public cdbAnalogSensorsSCADA dbAnalogSensorsSCADA;
        public cMyPlc
            (
            int accumulatorPort,
            S7.Net.CpuType cpuType,
            string plcIp,
            short plcRack,
            short plcSlot
            ) : base
            (
                accumulatorPort, 
                cpuType, 
                plcIp,
                plcRack,
                plcSlot
            )
        {
            dbAnalogSensorsSCADA = new(51, 2130, _s7ClientAccumulator, _s7Plc);
            AddS7db(dbAnalogSensorsSCADA);
        }
    }
}