// ===============================================================
//  ⚠ WARNING: THIS FILE IS AUTO-GENERATED BY S7SiCADA v1.0.0
// ---------------------------------------------------------------
//  DO NOT EDIT THIS FILE MANUALLY!
//  Any changes will be overwritten when the code is regenerated
//  and may cause unexpected behavior.
// ---------------------------------------------------------------
//  Created:       2025-10-14
//  Last Updated:  2025-10-14
//  Checksum:      0x12345678
// ===============================================================

// CHECKSUM
public static partial class SiCADA
{
    public static cMyPlc? MyPlc;
    public partial class cMyPlc : S7Accumulator
    {
        // DB_DECLARATIONS
        public cdbAnalogSensorsSCADA dbAnalogSensorsSCADA;
        // END_DB_DECLARATIONS
        public cMyPlc
            (
            int accumulatorPort,
            S7.Net.CpuType cpuType,
            string plcIp,
            short plcRack,
            short plcSlot
            ) : base
            (
                accumulatorPort, 
                cpuType, 
                plcIp,
                plcRack,
                plcSlot
            )
        {
            // DB_INSTANTIATIONS
            dbAnalogSensorsSCADA = new(51, 2130, _s7ClientAccumulator, _s7Plc);
            AddS7db(dbAnalogSensorsSCADA);
            // END_DB_INSTANTIATIONS
        }
    }
}
// END_CHECKSUM